name: Deploy Coding

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    steps: # 步骤
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@v2

      # 2. 设置pnpm包管理器
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      # 3. 安装nodejs
      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm" # 缓存

      # 4.安装依赖
      - name: Install deps
        run: pnpm install

      - name: Deploy
        env:
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }} # toKen私密变量
        run: |
          npx hexo -v # 查看版本
          rm -rf themes # 先删除再安装主题，解决hexo g构建时，缺失layout的问题
          git clone https://github.com/JS-banana/hexo-theme-next themes/next # 获取我的仓库hexo镜像
          npm run clean # 清理
          npm run build # 构建 
          npm run coding # 部署到 coding
